# Generated by Django 4.2 on 2025-04-04 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='invoiceitem',
            options={'ordering': ['weight'], 'verbose_name': 'Invoice Item', 'verbose_name_plural': 'Invoice Items'},
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='weight',
            field=models.IntegerField(default=0, null=True, verbose_name='Weight'),
        ),
    ]
