# Generated by Django 4.2 on 2025-03-19 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='total_amount',
            field=models.FloatField(default=0.0, null=True, verbose_name='Total Amount'),
        ),
    ]
