# Generated by Django 4.2 on 2025-03-19 00:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0002_invoice_total_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceitem',
            name='invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='invoice.invoice'),
        ),
    ]
