# Generated by Django 5.2.12 on 2026-03-25 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0003_historicalinvoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalinvoice',
            name='status_changed_on',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Status Changed On'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='status_changed_on',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Status Changed On'),
        ),
    ]
