# Generated by Django 4.2 on 2025-03-19 23:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('invoice', '0005_invoice_template'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoiceNote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('note', models.TextField()),
                ('createdon', models.DateTimeField(auto_now=True)),
                ('parent', models.UUIDField(blank=True, null=True)),
                ('meta', models.JSONField(blank=True, null=True)),
                ('createdby', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='invoice.invoice')),
            ],
            options={
                'ordering': ['createdon'],
            },
        ),
    ]
