# Generated by Django 4.2 on 2025-03-21 14:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0006_invoicenote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='template',
            field=models.ForeignKey(default='4851acab-e7ff-497d-864c-a3387257a4aa', on_delete=django.db.models.deletion.PROTECT, to='invoice.invoicetemplate'),
        ),
    ]
